### ISSUE TITLE
ID system enhancement

### ISSUE THREAD

**Issue by E-3P0** [Azurekuz/RPG-Task-Manager#112]
The ID system as-is is prone to bugs. It was originally thought of as a solution to duplicate titles, and each task would have a unique id, but the way it is implemented now different tasks across different tasklists can have the same id value, and many functions attempted to use it as an index which tended to break things.

This enhancement should include: Global Task counter (part of TaskManager) that is incremented and passed in to TaskList when a new task is created. Perhaps calculate in load function as sum of the size of all tasklists + 1 if a main task is selected. 
Some other notes:
-If a current task is completed or failed, it should be moved to the respective task list without changing the id, since moving the task does not change the global task count.
-When a task is selected (added to current or set as main task) it should get a new id and increment the global count since the selected task is not removed from the default/custom task list.

After this is done we can clean up some extra operations and functions that bypassed the buggy id system.

**Comment by Azurekuz** [comment]
Time Taken (so far): 1.75 hours

**Comment by Azurekuz** [comment]
+1.5 hours
Fixing some bugs, making tests pass, and resolving a merge conflict.

Time Taken: 3.25 Hours
