### ISSUE TITLE
Default Task Pool

### ISSUE THREAD

**Issue by E-3P0** [Azurekuz/RPG-Task-Manager#12]
How to demo:should pop up when user is trying to add a task, main tasks it will pop up automatically, however, it will be an option to view the task pool for side and daily tasks
Includes main, side, and daily tasks

**Comment by E-3P0** [comment]
4 default tasks put in by Eugene, should get more though

**Comment by Azurekuz** [comment]
Added four default tasks and some tests.

Time Taken. 0.5 hours.
