### ISSUE TITLE
Task Manager Class

### ISSUE THREAD

**Issue by cmartano** [Azurekuz/RPG-Task-Manager#29]

**Comment by Azurekuz** [comment]
How Demo:
- Show off that the interface is a lot more legible.
1. Quickly re-demonstrate that Task Managing still works.
2. Error Catching.
3. Make sure we can create deadline and quality tasks, show them off in the system.
4. Complete, in varying levels of success.
5. We show off an achievement being given to the user.

Added tests and functional code for:

Finding Tasks
Adding Tasks
Editing/Updating Tasks
Completing Tasks
Getting Current Tasks
Error Catching

Took 1.25 hours for partial functionality.

**Comment by E-3P0** [comment]
Added some methods to work with UI, 45 minutes
