### ISSUE TITLE
Task Object

### ISSUE THREAD

**Issue by cmartano** [Azurekuz/RPG-Task-Manager#3]
Main task class/object. 
Support for: completion, quality/difficulty, time-based, and different types

HTD: Successfully running unit tests of Task. Task commands working.

**Comment by E-3P0** [comment]
First commit - started tests, 30 mins

**Comment by E-3P0** [comment]
finished tests +15 mins

**Comment by E-3P0** [comment]
finished object/class code, adjusted tests slightly, all tests passing. +1hour, fits two hour estimate.
