### ISSUE TITLE
Sequence Diagrams

### ISSUE THREAD

**Issue by E-3P0** [Azurekuz/RPG-Task-Manager#7]

**Comment by E-3P0** [comment]
https://drive.google.com/file/d/12urRBzBuWt23uFDgzqaHYEAygWSiZ3w-/view complete task

**Comment by Azurekuz** [comment]
**DEMO:** Making sequence diagrams of obtaining achievements, and _maybe_ some barebones RPG functionality.

**Comment by Azurekuz** [comment]
Sequence diagram created for Achievement:
Time taken (so far): 0.5 hours
