### ISSUE TITLE
Failed Tasks

### ISSUE THREAD

**Issue by Azurekuz** [Azurekuz/RPG-Task-Manager#72]
List of failed tasks in user class. User can see list of failed tasks from TaskUI. Failed tasks are removed from current tasks and sent to failed task list. User can manually fail a task. Timed tasks that go past the time limit automatically fail.

How to demo:
We would create a task and let the time limit run out and then have that task be put in the failed task list

Estimate:3hr

**Comment by E-3P0** [comment]
List of failed tasks in user class. User can see list of failed tasks from TaskUI. Failed tasks are removed from current tasks and sent to failed task list. User can manually fail a task. Timed tasks that go past the time limit automatically fail.

**Comment by E-3P0** [comment]
Did a lot of this as part of Time Mechanics card and branch. Maybe close this card?
