### ISSUE TITLE
Select Tasks by ID

### ISSUE THREAD

**Issue by E-3P0** [Azurekuz/RPG-Task-Manager#76]
Since task IDs are also shown in toString, users can select tasks by ID in the UI (not just the name).

**Comment by Azurekuz** [comment]
**Demo:** When prompted to select a task, enter a numerical id, thus allowing tasks to be managed successfully aside from typing in their titles.

Selecting, Stopping, Editing, and Completing now work by ID.

Time Taken (so far): 0.5 Hours

**Comment by Azurekuz** [comment]
Resolved merge conflicts. 
+0.16 Hours

Time Taken (so far): 0.66 hours
